In [106]:
!python3 -m pip install numpy
!python3 -m pip install pandas

You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.


In [12]:
import numpy as np

test = np.array([1,2,3])
test

array([1, 2, 3])

In [108]:
np.zeros([5, 4, 3, 5])

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0

In [17]:
np.zeros_like([[2, 4, 5, 6],[1,2,3,4]])

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
np.ones([5,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.ones_like([[2,3,4,5],[12,2,2,2]])

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
np.empty([5,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
test = np.array([[1.1,4,5,6], [1,2,3,4]])
test.dtype

dtype('float64')

In [51]:
test_sub = test[0, :2].copy()
# test_sub
test[0, 0:2] = [33, 22]
test_sub

array([55., 44.])

In [54]:
test[0, 1]

22.0

In [57]:
import pandas as pd

ser = pd.Series([1,2,4,5])
ser

0    1
1    2
2    4
3    5
dtype: int64

In [74]:
ser2 = pd.Series([2,4,6,8], index=["a", "b", "c", "d"])
ser2["a"] = "asdf"
ser2

a    asdf
b       4
c       6
d       8
dtype: object

In [80]:
values = {
    "aa": [1,2,3,4,5],
    "bb": ["a", "b", "c", "c", "d"]
}
df = pd.DataFrame(values)
df

aa bb
0   1  a
1   2  b
2   3  c
3   4  c
4   5  d

In [87]:
df = pd.DataFrame(np.arange(6).reshape(3, 2), columns=["aa", "bb"], index=["a", "b", "c"])
df

aa  bb
a   0   1
b   2   3
c   4   5

In [97]:
df.columns = ['cc', 'dd']
df

cc  dd
a   0   1
b   2   3
c   4   5

In [99]:
df = df.rename(columns={'cc': 'aa'})
df

aa  dd
a   0   1
b   2   3
c   4   5

In [101]:
df.rename(columns={'aa': 'acc'}, inplace=True)
df

acc  dd
a    0   1
b    2   3
c    4   5

In [105]:
df = pd.read_csv('text.csv', sep='#')
df.to_csv('text2.csv', index=False)
# pd.read_excel('aaa.xls')